### PR TITLE
Switch router to httptreemux

### PR DESCRIPTION
**Pull request by guregu**
See: #14 

Seems to be backwards compatible, also not that much slower.

```
                                       new          old
BenchmarkShortRoute-8                   505 ns/op    492 ns/op
BenchmarkLongRoute-8                    566 ns/op    561 ns/op
BenchmarkDeepRoute-8                    857 ns/op    667 ns/op
BenchmarkDeepRouteUnicode-8            1068 ns/op    859 ns/op
BenchmarkSuperDeepRoute-8              1751 ns/op   1215 ns/op
BenchmarkParameter-8                    770 ns/op    534 ns/op
BenchmarkParameter5-8                  1761 ns/op   1009 ns/op
BenchmarkMiddleware-8                   528 ns/op    509 ns/op
BenchmarkMiddleware5-8                 1338 ns/op   1311 ns/op
BenchmarkMiddleware1Afterware1-8        726 ns/op    701 ns/op
BenchmarkMiddleware5Afterware1-8       1935 ns/op   1906 ns/op
BenchmarkMiddlewareAfterwareMiss-8      752 ns/op    624 ns/op
```

### CODE REVIEW

**Comment by guregu** [comment]
I think I'm gonna merge this soon. You can get faster numbers than the above benchmarks by not using Afterware (or Middleware). Inflexible routing seems to be a relatively big pain point in other frameworks.

**Comment by someone1** [comment]
Any update on if/when you'll merge this? There's apparently plans for httprouter v2 that will support this more flexible routing scheme but who knows how far out that is. Maybe a switch to that can be done at a later time if it turns out to be better than httptreemux?

**Comment by guregu** [comment]
@someone1 Sorry for the delay. I will merge it before 2016. I agree that it's a good idea to switch and possibly consider httprouter v2.

**Comment by solher** [comment]
Any update ? I'm currently looking for a net/context compatible alternative to Negroni and the use of httprouter is a dealbreaker for now. I started to use httptreemux after encountering the same issues.

**Comment by guregu** [comment]
Sorry for the wait everyone!

**Pull request merged**
